vysledek = len("slovo")
print(vysledek)
nulovy_retezec = len("")
print (nulovy_retezec)
uvozovky = len("Pokud je potřeba využít uvozovky, volí se vždy ty opačne oproti těm co ohraničují řetezec. př. 'slovo'")
print (uvozovky)
lomitko = len ("'běž do háje ty \"čubko\"'")
print(lomitko)
print('-\N{GREEK CAPITAL LETTER DELTA}-')
print('-\N{SECTION SIGN}-')
print('-\N{GRINNING CAT FACE WITH SMILING EYES}-')
print('-\x60-')
print('-\u30C4-')
print('-\U0001F0BD-')